package viewconsulta;

import controller.ControllerPessoa;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Pessoa;
import model.Usuario;
import principal.Conexao;

/**
 * @author Gelvazio Camargo
 */
public class consultaUsuarios extends javax.swing.JDialog {

    private static final int BUSCAR_TODOS = 0;

    public int codigo;
    public String nome;

    Cliente cli = new Cliente();
    Usuario usuario = new Usuario();
    
    /**
     * Creates new form consProduto
     */
    public consultaUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void filtraUsuarios(int codigoUsuario) {
        String sql = "select * from usuario order by usucodigo";
        atualizaTabelaUsuarios(sql);
    }

    public void atualizaTabelaUsuarios(String sql){
        DefaultTableModel model = (DefaultTableModel) tabelaConsultaUsuarios.getModel();
        
        // Limpa a tabela
        model.setRowCount(0);

        ArrayList<Usuario> listaUsuarios = Conexao.executaQuery(sql, usuario);
        for (Usuario auxUsuario : listaUsuarios) {
            model.addRow(new Object[]{
                auxUsuario.getCodigo(),
                auxUsuario.getNome(),
                auxUsuario.getEmail(),
                auxUsuario.getLogin()
            });
        }
    }
    
    public void filtraClientes(int codigoCliente) {
        // Seta os clientes do banco de dados na consulta
        String sqlPessoa = "select * from pessoa where coalesce(fg_vendedor, 0) = 1 and codigo = " + codigoCliente + " order by codigo";
        if (codigoCliente == BUSCAR_TODOS) {
            sqlPessoa = "select * from pessoa where coalesce(fg_vendedor, 0) = 1 order by codigo";
        }
        
        //atualizaTabelaClientes(sqlPessoa);
    }

    public void filtraClientesPorNome(String nome) {
        String sqlPessoa = "select * from pessoa where coalesce(fg_vendedor, 0) = 1 and nome ilike '%" + nome + "%' order by codigo";
        //atualizaTabelaClientes(sqlPessoa);        
    }

    public void atualizaTabelaClientes(String sqlPessoa){
        ControllerPessoa controllerPessoa = new ControllerPessoa();
        DefaultTableModel model = (DefaultTableModel) tabelaConsultaUsuarios.getModel();
        
        // Limpa a tabela
        model.setRowCount(0);

        ArrayList<Pessoa> listaPessoas = controllerPessoa.getAll(sqlPessoa);
        boolean temClientes = false;
        for (Pessoa auxPessoa : listaPessoas) {
            if(auxPessoa.getCodigo() > 0){
                temClientes = true;
            }
        }
        
        if(temClientes){
            JOptionPane.showMessageDialog(rootPane, "Listando vendedores encontrados...");
            
            for (Pessoa auxPessoa : listaPessoas) {
                model.addRow(new Object[]{
                    auxPessoa.getCodigo(),
                    auxPessoa.getNome(),
                    auxPessoa.getCpf(),
                    auxPessoa.getEndereco()
                });
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "vendedores não encontrados com o filtro informado!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsultaUsuarios = new javax.swing.JTable();
        edtConsulta = new javax.swing.JTextField();
        botaoTodos = new javax.swing.JRadioButton();
        botaoNome = new javax.swing.JRadioButton();
        botaoCodigo = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 620, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consulta de Usuários");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 660, -1));

        tabelaConsultaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "E-mail", "Login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaConsultaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaConsultaUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 640, 340));
        getContentPane().add(edtConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 620, -1));

        botaoTodos.setSelected(true);
        botaoTodos.setText("Todos");
        botaoTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTodosActionPerformed(evt);
            }
        });
        getContentPane().add(botaoTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        botaoNome.setText("Nome");
        botaoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        botaoCodigo.setText("Código");
        botaoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jButton1.setText("Pesquisar Usuário");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaConsultaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaUsuariosMouseClicked
        codigo = Integer.parseInt(String.valueOf(tabelaConsultaUsuarios.getModel().getValueAt(tabelaConsultaUsuarios.getSelectedRow(), 0)));
        nome = String.valueOf(tabelaConsultaUsuarios.getModel().getValueAt(tabelaConsultaUsuarios.getSelectedRow(), 1));
        dispose();
    }//GEN-LAST:event_tabelaConsultaUsuariosMouseClicked

    private void botaoTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTodosActionPerformed
        if (botaoTodos.isSelected()) {
            botaoNome.setSelected(false);
            botaoCodigo.setSelected(false);
        } else {
            botaoNome.setSelected(true);
        }

        edtConsulta.requestFocus();
        edtConsulta.selectAll();        
    }//GEN-LAST:event_botaoTodosActionPerformed

    private void botaoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCodigoActionPerformed
        if (botaoCodigo.isSelected()) {
            botaoTodos.setSelected(false);
            botaoNome.setSelected(false);
        } else {
            botaoNome.setSelected(true);
        }

        edtConsulta.requestFocus();
        edtConsulta.selectAll();
    }//GEN-LAST:event_botaoCodigoActionPerformed

    private void botaoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNomeActionPerformed
        if (botaoNome.isSelected()) {
            botaoTodos.setSelected(false);
            botaoCodigo.setSelected(false);
        } else {
            botaoTodos.setSelected(true);
        }

        edtConsulta.requestFocus();
        edtConsulta.selectAll();
    }//GEN-LAST:event_botaoNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atualizaConsultaUsuario();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public void atualizaConsultaUsuario(){
        DefaultTableModel model = (DefaultTableModel) tabelaConsultaUsuarios.getModel();
        model.setNumRows(0);
        //cli.setListaCli(cli.retornaClientes());

        if (botaoTodos.isSelected()) {
            filtraUsuarios(BUSCAR_TODOS);
        }
    }
    
    public void atualizaConsulta(){
        DefaultTableModel model = (DefaultTableModel) tabelaConsultaUsuarios.getModel();
        model.setNumRows(0);
        cli.setListaCli(cli.retornaClientes());

        if (botaoTodos.isSelected()) { //Todos
            filtraClientes(BUSCAR_TODOS);
        } else if (botaoCodigo.isSelected()) { //Código
            if(edtConsulta.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Informe o codigo do vendedor!");
            } else {
                // Pega o codigo da Consulta
                int codigoPesquisa = Integer.parseInt(edtConsulta.getText());
                filtraClientes(codigoPesquisa);                
            }
        } else if (botaoNome.isSelected()) {
            if(edtConsulta.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Informe o nome do vendedor!");
            } else {
                String nomeFiltrado = edtConsulta.getText().toUpperCase();
                filtraClientesPorNome(nomeFiltrado);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                consultaUsuarios dialog = new consultaUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botaoCodigo;
    private javax.swing.JRadioButton botaoNome;
    private javax.swing.JRadioButton botaoTodos;
    private javax.swing.JTextField edtConsulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable tabelaConsultaUsuarios;
    // End of variables declaration//GEN-END:variables
}
